# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_team_latest_index'),
        ('users', '0002_auto_20160206_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='challenge.Customer'),
            preserve_default=False,
        ),
    ]
