# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='custom',
            new_name='customer',
        ),
    ]
