# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20160206_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 2, 6, 20, 42, 22, 554761, tzinfo=utc), verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
