# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20160206_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='latest_index',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
