# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0004_team_latest_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customers_managed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
