# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20160207_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='manager',
            new_name='dietitian',
        ),
    ]
